<a href="https://colab.research.google.com/github/314sirius/SpaceWeather-Satellites/blob/main/spaceweather.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

if 'google.colab' in str(get_ipython()):
    from google.colab import drive
    drive.mount('/content/drive')

path = '/content/drive/MyDrive/Space/SpaceWeather/SPACE/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
columns=['Year', 'Day', 'Hour', 'Minute', 'Field_Mag_average, nT', 'Bz_GSE, nT', 'Speed, km/s', 'Proton_Density, n/cc','Flow_Pressure, nPa', 'S/C, Xgse,Re','S/C, Ygse,Re','S/C, Zgse,Re','AE-index, nT','SYM/H, nT','Proton_Flux_10', 'Proton_Flux_30', 'Proton_Flux_60']
len(columns)

17

In [ ]:
import pandas as pd
def load_space_data(file_path, columns, skiprows=0):
    """
    Loads a space weather data file (.lst) into a pandas DataFrame.

    Args:
        file_path (str): The path to the .lst file.
        columns (list): A list of column names for the DataFrame.
        skiprows (int): Number of rows to skip at the beginning of the file.

    Returns:
        pd.DataFrame: The loaded DataFrame.
    """
    df = pd.read_csv(file_path, sep=r'\s+', skiprows=skiprows, header=None)
    df.columns = columns
    return df

df2010_2012 = load_space_data(path+'omni_5min_2010_2012.lst', columns)
df2013_2017 = load_space_data(path+'omni_5min_2013_2017.lst', columns)
df2018_2021 = load_space_data(path+'omni_5min_2018_2021.lst', columns)
df2022_2026 = load_space_data(path+'omni_5min_2022_2026.lst', columns)

In [ ]:
df2010_2012.head()

,Year,Day,Hour,Minute,"Field_Mag_average, nT","Bz_GSE, nT","Speed, km/s","Proton_Density, n/cc","Flow_Pressure, nPa","S/C, Xgse,Re","S/C, Ygse,Re","S/C, Zgse,Re","AE-index, nT","SYM/H, nT",Proton_Flux_10,Proton_Flux_30,Proton_Flux_60
0,2010,1,0,0,3.02,-0.39,283.6,3.91,0.63,231.23,-89.13,13.00,4,1,0.26,0.19,0.18
1,2010,1,0,5,3.06,-0.18,284.1,3.90,0.63,231.22,-89.14,13.00,5,1,0.22,0.15,0.06
2,2010,1,0,10,3.12,0.26,284.9,3.65,0.59,231.22,-89.14,13.00,5,1,0.22,0.16,0.14
3,2010,1,0,15,3.05,0.42,284.5,3.63,0.58,231.22,-89.15,13.00,4,1,0.22,0.12,0.10
4,2010,1,0,20,3.03,0.70,282.9,3.53,0.57,231.21,-89.15,12.99,3,1,0.29,0.10,0.06

In [ ]:
df2022_2026['Speed, km/s'].value_counts()

Speed, km/s
99999.9    39977
383.2        224
390.4        221
414.8        217
386.9        217
           ...
869.8          1
841.9          1
845.6          1
845.1          1
888.6          1
Name: count, Length: 6225, dtype: int64

In [ ]:
len(df2010_2012)+len(df2013_2017)+len(df2018_2021)+len(df2022_2026)

1684512

In [ ]:
df = pd.concat([df2010_2012, df2013_2017, df2018_2021, df2022_2026], ignore_index=True)

In [ ]:
df.shape

(1684512, 17)

In [ ]:
import numpy as np

# Define the placeholder values to be replaced with NaN
placeholder_values = [99999.9, 99999.99, 9999.99, 999.99, 99.99]

# Replace placeholder values with NaN across the entire DataFrame
df.replace(placeholder_values, np.nan, inplace=True)

df.head()

,Year,Day,Hour,Minute,"Field_Mag_average, nT","Bz_GSE, nT","Speed, km/s","Proton_Density, n/cc","Flow_Pressure, nPa","S/C, Xgse,Re","S/C, Ygse,Re","S/C, Zgse,Re","AE-index, nT","SYM/H, nT",Proton_Flux_10,Proton_Flux_30,Proton_Flux_60
0,2010,1,0,0,3.02,-0.39,283.6,3.91,0.63,231.23,-89.13,13.00,4,1,0.26,0.19,0.18
1,2010,1,0,5,3.06,-0.18,284.1,3.90,0.63,231.22,-89.14,13.00,5,1,0.22,0.15,0.06
2,2010,1,0,10,3.12,0.26,284.9,3.65,0.59,231.22,-89.14,13.00,5,1,0.22,0.16,0.14
3,2010,1,0,15,3.05,0.42,284.5,3.63,0.58,231.22,-89.15,13.00,4,1,0.22,0.12,0.10
4,2010,1,0,20,3.03,0.70,282.9,3.53,0.57,231.21,-89.15,12.99,3,1,0.29,0.10,0.06

In [ ]:
df.isna().sum()

Year                          0
Day                           0
Hour                          0
Minute                        0
Field_Mag_average, nT     71154
Bz_GSE, nT                71154
Speed, km/s              142643
Proton_Density, n/cc     142643
Flow_Pressure, nPa       142643
S/C, Xgse,Re             142643
S/C, Ygse,Re             142756
S/C, Zgse,Re             142643
AE-index, nT                  0
SYM/H, nT                     0
Proton_Flux_10           622040
Proton_Flux_30           622040
Proton_Flux_60           622040
dtype: int64

In [ ]:
df.to_csv('SpaceWeather/SpaceWeather.csv', index=False)